### ISSUE TITLE
打开程序后，下载第二首歌时转换报错

### ISSUE THREAD

**Issue by caaaaaat6** [iKunpw/auto-ncmdump#1]
打开程序后，下载第二首歌时转换报错：

> Traceback (most recent call last):
>   File "autodump.py", line 35, in \<module\>
>   File "ncmdump\core.py", line 25, in dump
> PermissionError: [Errno 13] Permission denied: 'F:\\\\CloudMusic\\\\VipSongsDownload\\\\LizNoir - The Last Chance.ncm'
> [6216] Failed to excute scriipt autodump

希望两年没维护的作者能够看到

**Comment by pigajiu** [comment]
是刚下载完文件时网易云音乐还占用着这个文件然后程序去读取刚下好的文件时会出现这个权限问题，我修改了作者的代码加了个判断避免这种情况发生。[Redirect to new version](https://github.com/pigajiu/auto-ncmdump/releases/tag/1.1)
